BEGIN;
--
-- Create model Category
--
CREATE TABLE "biscuits_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(70) NOT NULL);
--
-- Create model UserData
--
CREATE TABLE "biscuits_userdata" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(100) NOT NULL UNIQUE, "address" varchar(100) NOT NULL, "city" varchar(100) NOT NULL, "country" varchar(100) NOT NULL, "phone" varchar(20) NULL, "postal" varchar(10) NULL, "date_joined" timestamp with time zone NOT NULL, "is_admin" boolean NOT NULL, "is_active" boolean NOT NULL, "is_staff" boolean NOT NULL, "is_superuser" boolean NOT NULL);
CREATE TABLE "biscuits_userdata_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "userdata_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "biscuits_userdata_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "userdata_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Order
--
CREATE TABLE "biscuits_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "uuid" varchar(50) NOT NULL UNIQUE, "status" varchar(50) NOT NULL, "owner_id" bigint NOT NULL);
--
-- Create model Product
--
CREATE TABLE "biscuits_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(70) NOT NULL, "description" text NOT NULL, "price" numeric(10, 2) NOT NULL, "stock" integer NOT NULL CHECK ("stock" >= 0), "illustration" varchar(100) NOT NULL, "category_id" bigint NOT NULL);
--
-- Create model OrderElement
--
CREATE TABLE "biscuits_orderelement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "related_order_id" bigint NOT NULL, "product_id" bigint NOT NULL);
CREATE INDEX "biscuits_userdata_email_79afc6ad_like" ON "biscuits_userdata" ("email" varchar_pattern_ops);
ALTER TABLE "biscuits_userdata_groups" ADD CONSTRAINT "biscuits_userdata_groups_userdata_id_group_id_01326e4c_uniq" UNIQUE ("userdata_id", "group_id");
ALTER TABLE "biscuits_userdata_groups" ADD CONSTRAINT "biscuits_userdata_gr_userdata_id_ad6d2e90_fk_biscuits_" FOREIGN KEY ("userdata_id") REFERENCES "biscuits_userdata" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "biscuits_userdata_groups" ADD CONSTRAINT "biscuits_userdata_groups_group_id_a3d95de0_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "biscuits_userdata_groups_userdata_id_ad6d2e90" ON "biscuits_userdata_groups" ("userdata_id");
CREATE INDEX "biscuits_userdata_groups_group_id_a3d95de0" ON "biscuits_userdata_groups" ("group_id");
ALTER TABLE "biscuits_userdata_user_permissions" ADD CONSTRAINT "biscuits_userdata_user_p_userdata_id_permission_i_3773f52b_uniq" UNIQUE ("userdata_id", "permission_id");
ALTER TABLE "biscuits_userdata_user_permissions" ADD CONSTRAINT "biscuits_userdata_us_userdata_id_4a25822e_fk_biscuits_" FOREIGN KEY ("userdata_id") REFERENCES "biscuits_userdata" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "biscuits_userdata_user_permissions" ADD CONSTRAINT "biscuits_userdata_us_permission_id_c7ed7377_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "biscuits_userdata_user_permissions_userdata_id_4a25822e" ON "biscuits_userdata_user_permissions" ("userdata_id");
CREATE INDEX "biscuits_userdata_user_permissions_permission_id_c7ed7377" ON "biscuits_userdata_user_permissions" ("permission_id");
ALTER TABLE "biscuits_order" ADD CONSTRAINT "biscuits_order_owner_id_d327804f_fk_biscuits_userdata_id" FOREIGN KEY ("owner_id") REFERENCES "biscuits_userdata" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "biscuits_order_uuid_9b8b15fe_like" ON "biscuits_order" ("uuid" varchar_pattern_ops);
CREATE INDEX "biscuits_order_owner_id_d327804f" ON "biscuits_order" ("owner_id");
ALTER TABLE "biscuits_product" ADD CONSTRAINT "biscuits_product_category_id_fc313a6d_fk_biscuits_category_id" FOREIGN KEY ("category_id") REFERENCES "biscuits_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "biscuits_product_category_id_fc313a6d" ON "biscuits_product" ("category_id");
ALTER TABLE "biscuits_orderelement" ADD CONSTRAINT "biscuits_orderelemen_related_order_id_f60a058a_fk_biscuits_" FOREIGN KEY ("related_order_id") REFERENCES "biscuits_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "biscuits_orderelement" ADD CONSTRAINT "biscuits_orderelemen_product_id_7358624c_fk_biscuits_" FOREIGN KEY ("product_id") REFERENCES "biscuits_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "biscuits_orderelement_related_order_id_f60a058a" ON "biscuits_orderelement" ("related_order_id");
CREATE INDEX "biscuits_orderelement_product_id_7358624c" ON "biscuits_orderelement" ("product_id");
COMMIT;
