# Generated by Django 5.0.6 on 2024-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE DE PAIEMENT', 'En attente de paiement'), ('EN ATTENTE DE LIVRAISON', 'En attente de livraison'), ('EN COURS DE LIVRAISON', 'En cours de livraison'), ('LIVRÉ', 'Livré'), ('ANNULÉ', 'Annulé')], default='EN ATTENTE DE PAIEMENT', max_length=50),
        ),
    ]
