# Generated by Django 3.2.20 on 2024-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='biscuits.ProductPicture/bytes/filename/mimetype'),
        ),
    ]
