# Generated by Django 5.0.6 on 2024-07-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
