# Generated by Django 5.0.6 on 2024-07-20 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.RenameModel(
            old_name='Panier',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Produit',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='role',
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='produits',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prix',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
