# Generated by Django 3.2.20 on 2024-09-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biscuits.product'),
        ),
    ]
