# Generated by Django 5.0.6 on 2024-07-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0002_delivery_rename_panier_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('mail', models.CharField(max_length=70)),
                ('phone', models.PositiveIntegerField()),
                ('adress', models.CharField(max_length=255)),
                ('postal', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='illustration',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biscuits.user'),
        ),
    ]
