# Generated by Django 5.0.7 on 2024-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0002_rename_adress_userdata_address_remove_userdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
