# Generated by Django 5.0.7 on 2024-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0003_alter_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
