# Generated by Django 5.0.6 on 2024-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente de paiement', 'Waiting for Payment'), ("En attente d'expedition", 'Waiting for Expedition'), ('En cours de livraison', 'In Delivery'), ('Livré', 'Delivered'), ('Annulé', 'Cancelled')], default='En attente de paiement', max_length=50),
        ),
    ]
