# Generated by Django 5.0.6 on 2024-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', to='biscuits.ingredient'),
        ),
    ]
