# Generated by Django 5.0.7 on 2024-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0005_order_orderelement_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
