# Generated by Django 5.0.6 on 2024-08-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0005_ingredient_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
