# Generated by Django 5.0.6 on 2024-07-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0005_remove_cart_user_userdata_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='adress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
