# Generated by Django 5.0.6 on 2024-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0006_remove_product_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
