# Generated by Django 5.0.6 on 2024-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0007_alter_userdata_adress_alter_userdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
