# Generated by Django 5.0.6 on 2024-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0008_alter_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='postal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
