# Generated by Django 5.0.6 on 2024-07-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0011_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
