# Generated by Django 5.0.6 on 2024-07-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
